import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useGameRoom } from '../contexts/GameRoomContext';
export default function Home() {
    const { user } = useAuth();
    const { getAvailableRooms } = useGameRoom();
    const availableRooms = getAvailableRooms();
    return (_jsxs("div", { className: "mobile-container fade-in", children: [_jsxs("div", { className: "logo", children: [_jsx("img", { src: "/logo.png", alt: "LaMap241" }), _jsx("div", { className: "mt-2 text-sm text-gray-400", children: "\uD83C\uDDEC\uD83C\uDDE6 Jeu de cartes" })] }), _jsxs("div", { className: "space-y-3", children: [_jsx(Link, { to: "/rooms", children: _jsxs("button", { className: "btn-primary flex items-center justify-center gap-2", children: ["\u2660 Rejoindre une partie", availableRooms.length > 0 && (_jsxs("span", { className: "bg-red-700 px-2 py-1 rounded-full text-xs", children: [availableRooms.length, " disponible", availableRooms.length > 1 ? 's' : ''] }))] }) }), _jsx(Link, { to: "/create-room", children: _jsx("button", { className: "btn-primary", children: "\u2665 Cr\u00E9er une partie" }) }), _jsx(Link, { to: "/game/vs-ai", children: _jsx("button", { className: "btn-primary", children: "\uD83E\uDD16 Jouer contre l'IA" }) }), _jsx(Link, { to: "/wallet", children: _jsxs("button", { className: "btn-primary flex items-center justify-center gap-2", children: ["\uD83D\uDCB0 Portefeuille", _jsxs("span", { className: "text-green-300 text-sm", children: ["(", new Intl.NumberFormat('fr-FR').format(user?.balance || 0), " FCFA)"] })] }) }), _jsx(Link, { to: "/rules", children: _jsx("button", { className: "btn-primary", children: "\u2663 R\u00E8gles du jeu" }) }), _jsx("button", { className: "btn-primary", onClick: () => {
                            const shareText = "Viens jouer à la carte sur La Map ! 🇬🇦🎴";
                            if (navigator.share) {
                                navigator.share({
                                    title: 'La Map',
                                    text: shareText,
                                    url: window.location.href,
                                });
                            }
                            else {
                                window.open(`https://wa.me/?text=${encodeURIComponent(shareText + ' ' + window.location.href)}`, '_blank');
                            }
                        }, children: "\uD83D\uDCF1 Partager l'app" })] }), _jsxs("div", { className: "mt-8 space-y-4", children: [_jsxs("div", { className: "bg-gray-800 p-4 rounded-lg border border-red-800", children: [_jsx("h3", { className: "font-bold text-yellow-400 mb-3", children: "\uD83D\uDCCA Tes stats" }), _jsxs("div", { className: "grid grid-cols-3 gap-4 text-center text-sm", children: [_jsxs("div", { children: [_jsx("div", { className: "text-lg font-bold text-blue-400", children: user?.stats?.gamesPlayed || 0 }), _jsx("div", { className: "text-gray-400", children: "Parties" })] }), _jsxs("div", { children: [_jsx("div", { className: "text-lg font-bold text-green-400", children: user?.stats?.gamesWon || 0 }), _jsx("div", { className: "text-gray-400", children: "Victoires" })] }), _jsxs("div", { children: [_jsx("div", { className: "text-lg font-bold text-yellow-400", children: new Intl.NumberFormat('fr-FR').format(user?.stats?.totalEarnings || 0) }), _jsx("div", { className: "text-gray-400", children: "FCFA gagn\u00E9s" })] })] })] }), availableRooms.length > 0 && (_jsxs("div", { className: "bg-gray-800 p-4 rounded-lg border border-green-800", children: [_jsx("h3", { className: "font-bold text-green-400 mb-3", children: "\uD83C\uDFAE Parties disponibles" }), _jsxs("div", { className: "space-y-2", children: [availableRooms.slice(0, 3).map(room => (_jsxs("div", { className: "flex justify-between items-center bg-gray-700 p-2 rounded", children: [_jsxs("div", { children: [_jsx("div", { className: "text-sm font-bold", children: room.name }), _jsxs("div", { className: "text-xs text-gray-400", children: ["par ", room.creator] })] }), _jsxs("div", { className: "text-right", children: [_jsxs("div", { className: "text-sm font-bold text-yellow-400", children: [room.bet, " FCFA"] }), _jsx(Link, { to: "/rooms", className: "text-xs text-blue-400", children: "Rejoindre \u2192" })] })] }, room.id))), availableRooms.length > 3 && (_jsxs(Link, { to: "/rooms", className: "block text-center text-blue-400 text-sm", children: ["Voir toutes les salles (", availableRooms.length, ") \u2192"] }))] })] })), _jsxs("div", { className: "bg-gray-800 p-4 rounded-lg border border-red-800", children: [_jsx("h3", { className: "font-bold text-yellow-400 mb-2", children: "\u2660\u2665\u2663\u2666 La Map" }), _jsx("p", { className: "text-sm text-gray-300", children: "La premi\u00E8re plateforme de jeu Garame du Gabon. Jouez avec vos amis ou contre l'IA, misez de l'argent r\u00E9el et gagnez !" })] })] })] }));
}
