import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useGameRoom } from '../contexts/GameRoomContext';
export default function Home() {
    const { user } = useAuth();
    const { getAvailableRooms } = useGameRoom();
    const availableRooms = Array.isArray(getAvailableRooms()) ? getAvailableRooms() : [];
    return (_jsx("div", { className: "mobile-container", children: _jsxs("div", { className: "lamap-home neon-theme", children: [_jsxs("div", { className: "lamap-logo", children: [_jsx("img", { src: "/logo.png", alt: "La Map" }), _jsx("div", { className: "subtitle", children: "\uD83C\uDDEC\uD83C\uDDE6 Jeu de cartes" })] }), _jsxs("div", { className: "action-grid", children: [_jsxs(Link, { to: "/create-room", className: "action-card", children: [_jsx("span", { children: "\u2665" }), _jsxs("p", { children: ["Cr\u00E9er", _jsx("br", {}), "une partie"] })] }), _jsxs(Link, { to: "/rooms", className: "action-card", children: [_jsx("span", { children: "\u2660" }), _jsxs("p", { children: ["Rejoindre", _jsx("br", {}), "une partie"] }), availableRooms.length > 0 && (_jsx("div", { className: "notif-badge", children: availableRooms.length }))] }), _jsxs(Link, { to: "/game/vs-ai", className: "action-card", children: [_jsx("span", { children: "\uD83E\uDD16" }), _jsxs("p", { children: ["Jouer", _jsx("br", {}), "contre l\u2019IA"] })] }), _jsxs(Link, { to: "/wallet", className: "action-card", children: [_jsx("span", { children: "\uD83D\uDCB0" }), _jsx("p", { children: "Portefeuille" })] })] }), _jsxs("div", { className: "lamap-section", children: [_jsx("h3", { children: "\uD83D\uDCCA Tes stats" }), _jsxs("div", { className: "stats-row", children: [_jsxs("div", { children: [_jsx("strong", { children: user?.stats?.gamesPlayed || 0 }), _jsx("span", { children: "Parties" })] }), _jsxs("div", { children: [_jsx("strong", { children: user?.stats?.gamesWon || 0 }), _jsx("span", { children: "Victoire" })] }), _jsxs("div", { children: [_jsx("strong", { children: user?.stats?.totalEarnings || 0 }), _jsx("span", { children: "FCFA gagn\u00E9s" })] })] })] }), availableRooms.length > 0 && (_jsxs("div", { className: "lamap-section", children: [_jsx("h3", { children: "\uD83C\uDFAE Parties disponibles" }), _jsx("div", { className: "avatar-row", children: availableRooms.slice(0, 3).map(room => (_jsxs("div", { className: "avatar-item", children: [_jsx("div", { className: "avatar-img" }), _jsx("div", { className: "avatar-name", children: room.creator })] }, room.id))) })] })), _jsxs("div", { className: "lamap-section", children: [_jsx("h3", { children: "\u2660\u2665\u2663\u2666 La Map" }), _jsx("p", { children: "La premi\u00E8re plateforme de jeu Garame du Gabon. Jouez avec vos amis ou contre l\u2019IA, misez de l\u2019argent r\u00E9el et gagnez !" })] })] }) }));
}
